### ISSUE TITLE
image resize to 512×1024 

### ISSUE THREAD

**Issue by akmaralAW** [yassouali/CCT#20]
Hello !

As I understood image size is adjusted by crop_size in config.json, which is 320. In this case images are resized into 320x320. How can I assign two different values for the width and height ? 

Thank you !

**Comment by SuzannaLin** [comment]
You can enter crop size as a list or tuple, like this:
![image](https://user-images.githubusercontent.com/69157347/96416926-f4187980-11f0-11eb-9cd3-89773c971619.png)
Don't forget to adjust both train_supervised and train_unsupervised, plus add a comma after the list. Not all sizes work due to the network convolutions.

**Comment by yassouali** [comment]
Hi @akmaralAW 
I see that @SuzannaLin answered your questions, thank you!

**Comment by akmaralAW** [comment]
@SuzannaLin , @yassouali  thank you so much for your help !
